New Framework
CarperAI/trlx pull request #1
Opened 2022-08-19 17:18 UTC by shahbuland

What I've done:
- Implementation of ILQL on IMDB positive review generation task (it runs and loss goes down, but haven't fully trained yet)
- Overall framework and utils that should be extendable to other algorithms
- Configs for training/models
- Example scripts to make use of models and show how certain utilities should be used and how training should be done

To still be done:
- PPO implementation
- Accelerate/multigpu support (Next priority) + mixed precision
- Full training of ILQL on sentiment task to test it out  

Let me know if you believe this is good to merge, or if I should finish some of the above features first.

2022-08-19 23:11 UTC, LouisCastricato requested changes

2022-08-19 23:11 UTC, LouisCastricato commented on framework/configs.py
> +class TrainConfig:
These should have default values!

2022-08-19 23:11 UTC, LouisCastricato commented on framework/configs.py
> +class ModelConfig:
Do we want a model type parameter here?

2022-08-19 23:11 UTC, LouisCastricato commented on framework/data/__init__.py
> +    state : Any = None
State and action should not be any

2022-08-19 23:11 UTC, LouisCastricato commented on framework/data/__init__.py
> +    masks : TensorType["BATCH", "SEQ_LEN"]
please always end files in a new line

2022-08-19 23:11 UTC, LouisCastricato commented on framework/data/sentiment.py
> +class SentimentGeneralElement:
Comments!

2022-08-19 23:11 UTC, LouisCastricato commented on framework/data/text_gen.py
> +class TextSimBatchElement(SimElement):
More comments

2022-08-19 23:11 UTC, LouisCastricato commented on framework/data/text_gen.py
> +    reward : float = None
end in new line

2022-08-19 23:11 UTC, LouisCastricato commented on framework/eval/sentiment.py
> +        sentiments = [pipe(chunk) for chunk in samples_chunks]
comments

2022-08-19 23:11 UTC, LouisCastricato commented on framework/eval/sentiment.py
> +from transformers import pipeline as PIPE
Why is pipe caps!

2022-08-19 23:11 UTC, LouisCastricato commented on framework/orchestrator/sentiment.py
> +    def make_experience(self, chunk_size = 512):
Comments!!!

2022-08-20 03:55 UTC, shahbuland commented on framework/configs.py
> +class ModelConfig:
model_arch is model_type 
arch as in architecture, though maybe changing to model_type would be more clear. done that

2022-08-20 03:59 UTC, shahbuland commented on framework/eval/sentiment.py
> +from transformers import pipeline as PIPE
Was a bandaid fix to resolve issue of pipeline being defined in two places once. Will change to more meaningful name.

2022-08-20 04:07 UTC, shahbuland commented on framework/data/sentiment.py
> +class SentimentGeneralElement:
Should I add comments to classes where their superclass has all the nessecary documentation already? It doesn't seem particularly helpful in that circumstance, though I've gone ahead and added comments where they seemed appropriate.

2022-08-20 04:11 UTC, shahbuland commented on framework/eval/sentiment.py
> +        sentiments = [pipe(chunk) for chunk in samples_chunks]
Have added (for this and orchestrator), check to see if they're sufficient.

2022-08-20 09:59 UTC, LouisCastricato commented on framework/eval/sentiment.py
> +        sentiments = [pipe(chunk) for chunk in samples_chunks]
lgtm

2022-08-20 10:00 UTC, LouisCastricato commented
Why did you rename PIPE to tfpipe? what does tf stand for?

2022-08-20 14:38 UTC, shahbuland commented
> Why did you rename PIPE to tfpipe? what does tf stand for?

transformers.pipeline => transformerspipeline => tfpipeline? 😅
I was trying to avoid renaming the pipeline parameter to orchestrator.

2022-10-03 19:08 UTC, merged