Add helpful and harmless example
CarperAI/trlx pull request #128
Opened 2022-12-08 19:04 UTC by reciprocated

2023-02-15 23:02 UTC, Dahoas commented on examples/hh/README.md
> +
Add line about `pip install tritonclient`

2023-02-15 23:02 UTC, Dahoas commented on examples/hh/configs/ppo_hh.yml
> +  model_path: "EleutherAI/gpt-j-6B"
Maybe let's make the default example use a smaller model so more people can run it

2023-02-17 01:06 UTC, jon-tow requested changes
Thanks, Max! I left a tiny nit for the `README.md`. 

On another note, I'm hitting an issue when using the GPU-hosting launch command from the `README.md` (for both ILQL and PPO) where the samples list provided to the ppo_hh `reward_fn` is empty causing an `IndexError`. Could you please try this? 

- Traceback Info: https://gist.github.com/jon-tow/e8aefbd0e7b06a1afc21dba38238d089

Note this only occurs when `--num_processes` is provided an odd number (quickly checked for 2, 4, and 6 processes fine).

2023-02-17 15:23 UTC, reciprocated commented
@jon-tow regarding your issue, If you upgrade to `accelerate==0.16.0` it will be resolved (I could reproduce it with `accelerate==0.15.0`)

2023-02-17 16:35 UTC, jon-tow approved these changes
@reciprocated I had forgotten about the `accelerate==0.15.0` metric bug 😅 This looks great from my end (not sure if Alex has any more feedback).

2023-02-21 21:31 UTC, merged