Add additional documentation for the random walk example
CarperAI/trlx pull request #208
Opened 2023-01-21 16:19 UTC by alan-cooney

2023-01-22 02:11 UTC, jon-tow requested changes
Thanks for putting this together @alan-cooney. I had some trouble running things locally. Can you fix the requested changes and provide a `wandb` report for both examples to ensure everything is working as expected? Thanks!

2023-01-22 02:11 UTC, jon-tow commented on examples/randomwalks/README.md
> +node in a graph.
Delete this it's a duplicate of the sentence above the `## Training` header

2023-01-22 02:11 UTC, jon-tow commented on examples/randomwalks/ppo_randomwalks.py
> +        reward_fn=lambda samples, p, o: metric_fn(samples, p, o)["optimality"],
Revert this. RL Trainer calls the `reward_fn` with the keyword args `samples, prompts, outputs` and this breaks the call.

2023-01-22 02:11 UTC, jon-tow commented on examples/randomwalks/randomwalks.py
> +        random_state: Numpy random state
Rever naming. `rng` is a very popular var name for an `np.random.RandomState` instance.

2023-01-22 02:11 UTC, jon-tow commented on examples/randomwalks/README.md
> +on tow optimal the path is compared to the shortest possible (bounded in [0,
Fix misspelling:
> The reward is based on ~~tow~~ how

2023-01-22 02:11 UTC, jon-tow commented on examples/randomwalks/randomwalks.py
> +        _outputs: Optional[List[str]] = None
Revert these, they are unused.

2023-01-22 02:11 UTC, jon-tow commented on examples/randomwalks/randomwalks.py
> +            "lengths": sample_lengths,
Revert this to `lengths` instead of `sample_lengths` to avoid type errors (`sample_lengths` is `Long`)

2023-01-22 09:07 UTC, alan-cooney commented
Thanks for the quick review @jon-tow 

PPO results - https://wandb.ai/alancooney/trlx/runs/eo1vxg53
ILQL results - https://wandb.ai/alancooney/trlx/runs/onfn4je1

## Typings fix

By the way, I had to fix the typings in trlx/trlx.py so that they work with the approach you prefer here. This fix is needed in any case as the typings were incorrect (the metric function only takes samples - it's just the reward function that also takes prompts and outsputs):

https://github.com/CarperAI/trlx/blob/84a07113d8ced1497c5a7941a02f9c534bb4e185/trlx/trainer/accelerate_base_trainer.py#L357

However, I'm happy to move this fix to a different PR if you want to keep the commit history clean (it's a small change, but it doesn't really belong here).

2023-01-22 20:30 UTC, jon-tow requested changes
> By the way, I had to fix the typings in trlx/trlx.py so that they work with the approach you prefer here. This fix is needed in any case, as the typings were incorrect (the metric function only takes samples - it's just the reward function that also takes prompts and outputs):
> 
> https://github.com/CarperAI/trlx/blob/84a07113d8ced1497c5a7941a02f9c534bb4e185/trlx/trainer/accelerate_base_trainer.py#L357
> 
> However, I'm happy to move this fix to a different PR if you want to keep the commit history clean (it's a small change, but it doesn't really belong here).

Oh huh; this slipped under the radar. Thanks for the find 🙏 `metric_fn` should match the `reward_fn` signature  and be called as 
```python
metrics = self.metric_fn(
  samples=str_samples,
  prompts=str_prompts,
  outputs=str_outputs,
)
```
on the line that you've highlighted. It's a small enough change that we can squeeze it into this PR. Let me know if that's alright with you! Once that's done we should be good to merge 👍

2023-01-22 20:30 UTC, jon-tow commented on trlx/trlx.py
> +    metric_fn: Optional[Callable[[List[str]], Dict[str, List[float]]]] = None,
Revert this type-hint because it's actually what we want haha

2023-01-22 20:30 UTC, jon-tow commented on trlx/trlx.py
> +        metric_fn ( Optional[Callable[[List[str]], Dict[str, List[float]]]]):
Revert this docstring change for reasons outlined above

2023-01-22 20:30 UTC, jon-tow commented on examples/randomwalks/ppo_randomwalks.py
> +        metric_fn=metric_fn,
Revert to match the intended `metric_fn` signature

2023-01-22 21:26 UTC, alan-cooney commented
Makes sense! All done, and I've checked the runs work as well:

PPO - https://wandb.ai/alancooney/trlx/runs/agtv55vb
ILQL - https://wandb.ai/alancooney/trlx/runs/feb6oky6

2023-01-22 23:47 UTC, reciprocated commented
Have to say this is a great work! However it's rather peculiar that I cannot reproduce your PPO wandb run from this branch despite my run being identical as from the `main`. It seems like a dependency difference and if it's not too laborious can you make a run from the `main` as well on your side just to confirm the suspicion? Thanks!

https://wandb.ai/sorry/trlx/reports/random_walks_document-v-main--VmlldzozMzkyNjE1

2023-01-23 10:08 UTC, alan-cooney commented
Sure, this seems plausible. I get the same results on main as on this branch, so I think it's all fine.

Main - https://wandb.ai/alancooney/trlx/runs/ixhfy261
This branch - https://wandb.ai/alancooney/trlx/runs/agtv55vb (from above)

As I understand it, CUDA + different hardware can cause different results with the same random seed. But in terms of environments, I'm using this docker image https://github.com/CarperAI/trlx/pull/196 and then `pip install`, if you want to reproduce it.

2023-01-31 00:59 UTC, jon-tow approved these changes
I can also reproduce the runs from `main`:
- PPO: https://api.wandb.ai/links/jon-tow/879xsiiw 
- ILQL: https://api.wandb.ai/links/jon-tow/jbgyq8yg

Thanks a bunch, @alan-cooney!

2023-01-31 01:00 UTC, merged