Docs
CarperAI/trlx pull request #71
Opened 2022-10-26 16:32 UTC by shahbuland

- Add docstrings to any major objects missing them
- Add docstrings to configs and data classes
- Add RTD style documentation

2022-10-26 17:07 UTC, thedch commented on docs/source/configs.rst
> +**PPO**
Any reason to add trailing whitespace?

2022-10-26 17:08 UTC, thedch commented on trlx/data/ppo_types.py
> +    query_tensor : TensorType["query_size"]
Why add the space before and after the colon? Does this pass black?

2022-10-27 22:36 UTC, shahbuland commented
@thedch Bit confused by results of black. Fixed the simple things, but code-quality test still failing. If you have time, could you take a look and give some pointers on where things are going wrong?

2022-10-28 11:14 UTC, reciprocated requested changes
lgtm

2022-10-28 11:14 UTC, reciprocated commented on README.md
> +**[Documentation](https://trlX.readthedocs.io)**
there are 4 links to the documentation, which are redundant?

2022-10-28 11:14 UTC, reciprocated commented on trlx/data/configs.py
> +    :param checkpoint_interval: Save model every save_interval steps
checkpoint_interval here

2022-10-28 15:43 UTC, LouisCastricato commented
@shahbuland answer the comments and lets merge.

2022-10-28 17:32 UTC, shahbuland commented on trlx/data/configs.py
> +    :param checkpoint_interval: Save model every save_interval steps
Done, for this and  readme change

2022-10-28 17:33 UTC, LouisCastricato approved these changes

2022-10-28 17:33 UTC, LouisCastricato commented
Will merge after check passes.

2022-10-28 17:35 UTC, merged